"""
Django settings for django_password_generator project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$gyrj@=j3ozd1qefxw-@j5efiw#-x0b@_1$di*!^tg=yv00cte' #код безопасности

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin', # Административная панель (сайт /admin)
    'django.contrib.auth', # Система аутентификации: пользователи, группы, права, пароли
    'django.contrib.contenttypes', # Фреймворк для "привязки" моделей друг к другу (нужен для auth и admin)
    'django.contrib.sessions', # Управление сессиями (сохраняет состояние пользователя между запросами)
    'django.contrib.messages', # Однострочные всплывающие сообщения ("Пароль изменён", "Статья сохранена")
    'django.contrib.staticfiles', # Обработка статических файлов: CSS, JS, изображения
]
# список всех приложений (модулей), которые активны
# Django использует этот список, чтобы знать, какие модели, шаблоны, статические файлы и команды нужно загрузить.

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware', # Безопасность: HTTPS-редиректы, заголовки HSTS, XSS-защита
    'django.contrib.sessions.middleware.SessionMiddleware', # Привязывает сессию к каждому запросу (через cookies)
    'django.middleware.common.CommonMiddleware', # Перенаправления с www и без, обработка PREPEND_WWW, APPEND_SLASH
    'django.middleware.csrf.CsrfViewMiddleware', # Защита от CSRF-атак (подделка межсайтовых запросов) — важен для форм и POST-запросов
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Привязывает текущего пользователя к запросу (request.user)
    'django.contrib.messages.middleware.MessageMiddleware', # 	Поддерживает систему однострочных сообщений (messages.success(request, "..."))
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # Защита от clickjacking (встраивания вашего сайта в iframe злоумышленником)
]
# промежуточное программное обеспечение — это "слои" обработки,
# через которые проходит каждый HTTP-запрос от браузера и HTTP-ответ от сервера

ROOT_URLCONF = 'django_password_generator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_password_generator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
